---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

# workaround for Connection failure: [ASN1] nested asn1 error (_ssl.c:4174)
- name: Add Docker GPG key.
  command: rpmkeys --import "{{ docker_yum_gpg_key }}"

# workaround for Connection failure: [ASN1] nested asn1 error (_ssl.c:4174)
- name: Add Docker repository.
  shell: curl "{{ docker_yum_repo_url }}" -o "/etc/yum.repos.d/docker-{{ docker_edition }}.repo"
  args:
    creates: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'

- name: Configure Docker Nightly repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-nightly'
    option: enabled
    value: '{{ docker_yum_repo_enable_nightly }}'
    mode: 0644
    no_extra_spaces: true

- name: Configure Docker Test repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-test'
    option: enabled
    value: '{{ docker_yum_repo_enable_test }}'
    mode: 0644
    no_extra_spaces: true

- name: Configure containerd on RHEL 8.
  block:
    - name: Ensure container-selinux is installed.
      package:
        name: container-selinux
        state: present

    - name: Ensure containerd.io is installed.
      package:
        name: containerd.io
        state: present
  when: ansible_distribution_major_version | int >= 8
